# Generated by Django 2.2.5 on 2021-06-25 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addressid', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.CharField(blank=True, max_length=25, null=True)),
                ('city', models.CharField(blank=True, max_length=25, null=True)),
                ('state', models.CharField(blank=True, max_length=25, null=True)),
                ('zipcode', models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventcode', models.AutoField(primary_key=True, serialize=False)),
                ('eventname', models.CharField(max_length=45)),
                ('missiondesc', models.CharField(blank=True, max_length=225, null=True)),
                ('dateofvolunteer', models.DateField(blank=True, null=True)),
                ('attendingneed', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True)),
                ('phonenumber', models.IntegerField(blank=True, null=True)),
                ('numberattended', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True)),
                ('objectivedesc', models.CharField(blank=True, max_length=225, null=True)),
                ('addressid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('volunteerid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('respdesc', models.CharField(blank=True, max_length=45, null=True)),
                ('addressid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteerevent',
            fields=[
                ('volunteereventid', models.AutoField(primary_key=True, serialize=False)),
                ('requestdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('signupdate', models.DateField(blank=True, null=True)),
                ('eventcode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Event')),
                ('volunteerid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='RegisterInfo',
            fields=[
                ('registerid', models.AutoField(primary_key=True, serialize=False)),
                ('cellphone', models.IntegerField(blank=True, null=True)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('dateofbirth', models.DateField(blank=True, null=True)),
                ('addressid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Address')),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('officerid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('respdesc', models.CharField(blank=True, max_length=45, null=True)),
                ('addressid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('officeid', models.AutoField(primary_key=True, serialize=False)),
                ('officename', models.CharField(max_length=45, unique=True)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('officerid', models.ForeignKey(blank=True, db_column='officerid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Officer')),
            ],
        ),
        migrations.CreateModel(
            name='Jobtitle',
            fields=[
                ('jobtitleid', models.AutoField(primary_key=True, serialize=False)),
                ('jobtitle', models.CharField(blank=True, max_length=45, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('officerid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Officer')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='officerid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Officer'),
        ),
    ]
